version: '3'

services:
  java:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: society

  front:
    build:
      context: front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
