api:
    prefix: /api
jwt:
    lifetime: 30m
    secret: 3C5D269FEA31E8DAFCF6956275A3DLKSDFJLKS:DJ98Y*SDF&^&*SDTFHJSDBGKFSDUYYTF*&SDYF*(DUHSFLKSDNJHGUISHY&G*T*&SUJDGF
spring:
    datasource:
        password: postgres
        url: jdbc:postgresql://db:5432/society
        username: postgres
    jpa:
        show-sql: true
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
paths:
    files: /app/files/
    users: /app/users/
    posts: /app/posts/
